### ISSUE TITLE
Open/close parenthesis no longer works when using autocomplete? 

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#123]
Is it just me, but it seems that the opening/closing parenthesis are not working when selecting a function from the completion menu?

I think before it was inserting `()` and placing the cursor right inside ready to use arguments. It seems that I have to type them manually now.

![Peek 2024-04-19 13-45](https://github.com/R-nvim/R.nvim/assets/4519221/c79af6de-5dad-4647-8461-d74e1752f80d)

**Comment by jalvesaq** [comment]
> I think before it was inserting () and placing the cursor right inside ready to use arguments. It seems that I have to type them manually now.

When I insert the opening parenthesis after a function name, the completion menu with the list of arguments appears immediately.

**Comment by jalvesaq** [comment]
> Suggestion: could be nice to automatically add the = character when it is not present in the parameter list (will save some keystrokes :))

It makes sense. Although the `=` character isn't in the output of `args()`, if the user is going to type it, the `=` character will have to be typed too.

**Comment by PMassicotte** [comment]
> > I think before it was inserting () and placing the cursor right inside ready to use arguments. It seems that I have to type them manually now.
> 
> When I insert the opening parenthesis after a function name, the completion menu with the list of arguments appears immediately.

yeah me also, but I mean when you select the function, it writes it up in the buffer but without the `()`.

**Comment by PMassicotte** [comment]
> > Suggestion: could be nice to automatically add the = character when it is not present in the parameter list (will save some keystrokes :))
> 
> It makes sense. Although the `=` character isn't in the output of `args()`, if the user is going to type it, the `=` character will have to be typed too.

For example

```r
[ins] r$> args(lm)
function (formula, data, subset, weights, na.action, method = "qr", 
    model = TRUE, x = FALSE, y = FALSE, qr = TRUE, singular.ok = TRUE, 
    contrasts = NULL, offset, ...) 
```

When we build the argument list, we could check if it ends up with `=` and if not, insert it?

**Comment by jalvesaq** [comment]
> When we build the argument list, we could check if it ends up with = and if not, insert it?

No need to check. We can simply always insert it unless it is `...`.

**Comment by jalvesaq** [comment]
> yeah me also, but I mean when you select the function, it writes it up in the buffer but without the (). Maybe it is just a matter of preference :)

This would almost always be useful, but not when using a function such as `tapply()` which receives a function as its third argument.

**Comment by PMassicotte** [comment]
> > yeah me also, but I mean when you select the function, it writes it up in the buffer but without the (). Maybe it is just a matter of preference :)
> 
> This would almost always be useful, but not when using a function such as `tapply()` which receives a function as its third argument.

Ah yeah you are right, did not thought about this :) Well I do not have a strong feeling about it :)

**Comment by jalvesaq** [comment]
Nvim-R's omni completion shows the default value of arguments:

![image](https://github.com/R-nvim/R.nvim/assets/891655/3ed6a712-4757-4a31-840d-2be294b3e900)

This is useful because the user can immediately realise that there is no need to insert the argument if the argument has a pre-defined value and the value is what he/she would insert. This was the advantage of having the `=` sign only for arguments with default values.

**Comment by PMassicotte** [comment]
ah I see, did not realize it. I will close it as I can see that both ways are perfectly fine.

**Comment by jalvesaq** [comment]
I think always adding the `=` is a good idea, but I have to find the best way of informing [cmp-r](https://github.com/R-nvim/cmp-r) users the default value of an argument.

**Comment by PMassicotte** [comment]
ok I will re-open it :) I will think about a good way on my side. Tx you much

**Comment by jalvesaq** [comment]
The branch `compl_arg` on `R.nvim` and the branch with the same name in `cmp-r` include a proposal of how to show the default value of argument items:

https://github.com/R-nvim/R.nvim/tree/compl_arg
https://github.com/R-nvim/cmp-r/tree/compl_arg

![image](https://github.com/R-nvim/R.nvim/assets/891655/c24a9b87-d661-4af9-b201-527ca0621bdc)

The `=` symbol is added to the completion of all arguments because if the user is going to use the name of the argument the `=` symbol will be needed too. The space after the symbol is removed by `nvim-cmp`.

**Comment by PMassicotte** [comment]
Trying it now!

**Comment by PMassicotte** [comment]
Works perfectly fine on my side!

**Comment by jalvesaq** [comment]
I'm fixing other bugs before doing a pull request...

Suppose you compare the completion in the two cases below where the vertical bar indicates the cursor position when manually triggering `cmp` completion. In that case, you will note that the completion of `ddd` doesn't happen in the second `summary`:

```r
aaa <- rnorm(100)
bbb <- rnorm(100)
ddd <- data.frame(aaa, bbb)
mmm <- lm(aaa ~ bbb)
summary(aaa, dd|)
summary(mmm, dd|)
```

This bug was fixed in the last commit. But there is another bug that I still have to fix. We don't get the summary of the columns of data frames from the `datasets` package. For example, when completing `rock$shape`, if we select `shape` in the completion menu, we don't get its summary:

```r
rock$shape
```

**Comment by PMassicotte** [comment]
Great! I just tested with the latest commit and I am getting the summary `rock$shape`.

![image](https://github.com/R-nvim/R.nvim/assets/4519221/6ad3eb34-fd24-4704-8f54-e6744d5deb2a)

**Comment by jalvesaq** [comment]
Certainly, there are some bugs in uncommon use cases, but I believe these branches already have enough improvements to be merged. I'll do the pull request, but, if you are aware of auto-completion needing improvement, add a comment, please.
