### ISSUE TITLE
Possible resource to add to the wiki

### ISSUE THREAD

**Issue by seb-mueller** [R-nvim/R.nvim#155]
First of all I wanted to say good job on creating this new repo. 
I've finally got round to try it and it's really nice!

In the process I've adapted my config to [Lazyvim](https://www.lazyvim.org) and came accross this rather useful resource that outlines how to set up R on neovim (including this repo!) and thought to share it since it could be used as inspiration or included in the wiki as an alternative pathway to set up neovim for R:
https://www.lazyvim.org/extras/lang/r

**Comment by jalvesaq** [comment]
Thanks! I added the link to https://github.com/R-nvim/R.nvim/wiki/Configuration

We can change the section title to "Other examples" if someone finds other links to add.

**Comment by jalvesaq** [comment]
It would be a good addition. Please, go ahead and edit the Wiki.

My two examples were focused on configurations that did little more than install the dependencies. I had to add configuration for `nvim-treesitter` and `nvim-cmp` because otherwise they wouldn't work. But it is good to have other examples that add more functionality.

**Comment by seb-mueller** [comment]
Just tried to edit, but the wiki seems not to be editable for me (at least not through github interface). 
Not sure how its done normally, maybe cloning?

**Comment by jalvesaq** [comment]
It should work now:
![image](https://github.com/R-nvim/R.nvim/assets/891655/9400b47b-6525-4cd0-82bb-3ce38d36e892)
