### ISSUE TITLE
Nvim variable to check if R is busy

### ISSUE THREAD

**Issue by kkanden** [R-nvim/R.nvim#284]
Is there a way to retrieve information on whether R is currently busy? I would like to add an element to my lualine status line which would change based on the state of R. I see in the documentation mention of `r_is_busy` variable but I don't know how I could access it. Is it possible to do what I want to do with what's accessible right now?

**Comment by PMassicotte** [comment]
I do not think it is currently available, but should not be that hard to implement. @jalvesaq ?

**Comment by jalvesaq** [comment]
It would be easy. But I'm not convinced of the benefit of having it because R itself gives us visual feedback of when it's busy or ready: _the prompt string is output only when R is ready for new commands_. The variable `r_is_busy` is compiled only for Windows because R will crash if we run a command through nvimcom when it's busy. On Unix, we can queue commands through a pipe to be ran automatically by R when its ready. This isn't possible on Windows.

**Comment by jalvesaq** [comment]
I'm closing the issue because, in addition to what I have already said, I'm also worried about the possibility of getting concurrent messages arriving simultaneously on Neovim. This may cause new bugs. However, I see no problem if someone wants to implement, carefully test, and maintain the requested feature.
