### ISSUE TITLE
Cannot get active window info

### ISSUE THREAD

**Issue by lokesh-krishna** [R-nvim/R.nvim#72]
I get the following error (please ignore the `headlines.nvim` error, still figuring that one out) whenever I open a Quarto document. Never happens with R scripts. As far as I can see, it doesn't impact functionality. 

```
Cannot get active window info on your system.
Please, do a pull request fixing the problem.
See: R.nvim/lua/r/utils.lua
```

Would still like to know what the problem is and how I can fix it. 

![grim-06-03-2024-06-26-47](https://github.com/R-nvim/R.nvim/assets/20235646/6b693e05-a45e-47c9-ab45-dc5fcc6c7751)

**Comment by jalvesaq** [comment]
This is a temporary invitation for early adopter users of `R.nvim` to fix an issue that is system-specific and that I can't fix. In the two systems that I can access on my laptop (Xorg and the Sway window manager), the PDF viewer window and the browser window may be focused after the corresponding document is generated. For those editing Rnoweb files, the terminal window might be focused during SyncTeX backward search. I know that it will be easy to write an Applescript command to focus the windows on Mac OS X, but I can't write it because I don't have access to a Mac to test the command. I'm not sure if Gnome, KDE, and other environments on Wayland have commands to focus windows. I know that it used to be possible to do this on Microsoft Windows, but I don't know if it still is.

If I didn't put this warning there, you would never know that this feature is missing from your system.

**Comment by lokesh-krishna** [comment]
Thanks! I'm presently on Hyprland. I'll check to see if this is possible there. In the meantime, is there a way to suppress this warning?

**Comment by jalvesaq** [comment]
You can put in your config table: `active_window_warn = false`.
But we may let this issue open until we delete the warning from `lua/r/utils.lua`.

**Comment by krissen** [comment]
I appreciate the effort to raise awareness about system bugs etc., but just want to mention that this is a rather annoying way of approaching it. Even a message that doesn't require my active input would be intrusive, but less so. 

Specifically what functionality am I missing due to this bug? My two cents would be to focus on that, and have a sticky or something in the README or issues or some such, where users *who are looking for said functionality* can see the reason why it isn't working, and can take appropriate measures (bug reporting upstream etc.).

Alternatively, if you want to keep the current (very effective) way of informing users, do mention it clearly in the README, that this is a known issue; this is the rationale for the current approach. 

But for me, personally, I just migrated from Nvim-R and just want to get R.nvim working without something nagging at me. My focus is on the nagging rather than the underlying problem *because I've yet to experience the actual issue.*

**Comment by jalvesaq** [comment]
We are still fixing bugs introduced with the conversion from VimScript to Lua (see the pull request that I merged a few minutes ago). But, after a few months, I agree that it's time to convert the warning into a subsection of _Know bugs_.
