### ISSUE TITLE
Change default indentation style?

### ISSUE THREAD

**Issue by wurli** [R-nvim/R.nvim#98]
One of the most important changes for me when setting up R.nvim was to change the default indentation style:

``` Lua
vim.g.r_indent_align_args = 0
```
This changes the indentation behaviour from this:
``` R
paste(
      ... # <- carriage return aligns cursor with `(` from prev line
```
To this:
``` R
paste(
  ... # <- carriage return adds a single layer of indentation
```

People of course have different opinions about which style is better, so in my view it would be best to:
* Make this setting easy to configure (done)
* Make the documentation for this setting easier to find - I'm not sure I would have been able to track it down without finding a [relevant issue](https://github.com/jalvesaq/Nvim-R/issues/286#issuecomment-367521538_) from Nvim-R.
* Provide a default which agrees with an industry standard. The [Tidyverse style guide](https://style.tidyverse.org) is by far the most popular style guide for R, and this advises the latter style:

> ``` R
> # Good
> do_something_very_complicated(
>   something = "that",
>   requires = many,
>   arguments = "some of which may be long"
> )
> 
> # Bad
> do_something_very_complicated("that", requires, many, arguments,
>                               "some of which may be long"
>                               )
> ```
> (From The tidyverse style guide, on [Syntax/Long lines](https://style.tidyverse.org/syntax.html#long-lines))

I'm enjoying this plugin so much - thank you for creating it and generously making it available to the world!

**Comment by jalvesaq** [comment]
The indentation is defined in the official Vim runtime file `indent/r.vim`, not by `R.nvim` or `Nvim-R`. I used to be the maintainer of the Vim runtime files for R, but no longer. See: https://github.com/vim/vim/blob/master/runtime/indent/r.vim

I'm no longer the maintainer of the Vim runtime files for R because I only use Neovim which (with tree-sitter) doesn't use the syntax and indent scripts from Vim. The ftplugin scripts are still used, but lately, I was wasting my time adding features that Lua plugins don't require to work. For example, in [this commit](https://github.com/jalvesaq/R-Vim-runtime/commit/485865b89560b58be989b2665c36576b29133439), I turned the value 'commentstr' dynamic, but [Comment.nvim](https://github.com/numToStr/Comment.nvim) uses tree-sitter instead of 'commentstr' to define the comment string. So, I implemented a feature that would be useful only for Vim, not Neovim while I no longer use Vim to see if the feature works well or has bugs.

**Comment by jalvesaq** [comment]
Please, see also: https://github.com/jalvesaq/Nvim-R/issues/577#issuecomment-1892587154

**Comment by wurli** [comment]
Thank you, your explanation is much appreciated. 

So if I understand correctly, the `vim.g.r_indent_align_args` setting comes from the vim runtime file `indent/r.vim`, but Neovim uses treesitter for indentation. Does treesitter then make use of this parameter? I'm a bit confused as to why setting `vim.g.r_indent_align_args = 0` worked if Neovim doesn't use the indentation scripts from Vim.

**Comment by jalvesaq** [comment]
Neovim still uses the syntax and indent files by default, but Neovim's team is investing in a tree-sitter-based solution as a replacement. Currently, you have to install [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) and explicitly enable highlighting and indenting via `treesitter`. I already have syntax highlighting via `treesitter` enabled, but not indenting yet. Anyway, the `indent/r.vim` script was the one I disliked most because it's too big, slow, and still has bugs.  I decided to abandon the whole [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime) repository and patiently wait for the `treesitter` indenting to become better than Vim's one.

**Comment by jalvesaq** [comment]
In summary, at least for R and Quarto:

- Syntax highlighting is better with `treesitter` than with Vim's syntax scripts.
- We don't need complex features in ftplugin scripts if using `treesitter`.
- Vim's indenting is still better in my opinion, but I'm tired of maintaining it.

**Comment by wurli** [comment]
I see - all makes sense now.

I've given treesitter's indentation a spin and I agree with you - even after some basic testing it feels like Vim does a better job, at least with R. For example, with the following text:

``` R
paste(
  "foo",
  )
```

When you type the final closing parenthesis, Vim will automatically unindent it to align with the 'p' in `paste` - treesitter doesn't do this for now.

Hopefully the unmaintained Vim indentation will suffice to carry things over until treesitter indentation matures.

Many thanks again!

**Comment by PMassicotte** [comment]
Just chiming in, I am using this to help me with indentation.

```lua
return {
    "Wansmer/treesj",
    keys = {
        {
            "<leader>m",
            "<CMD>TSJToggle<CR>",
            "Toggle Treesitter Join",
        },
    },
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    config = function()
        require("treesj").setup({
            max_join_length = 240,
        })
    end,
}
```
